---
title: "HW3"
author: "Joyce, Yameili, Tamires"
date: "10/4/2020"
output: html_document
---
```{r}
load("~/Desktop/.RData")
attach(dat_NYC)
borough_f <- factor((in_Bronx + 2*in_Manhattan + 3*in_StatenI + 4*in_Brooklyn + 5*in_Queens), levels=c(1,2,3,4,5),labels = c("Bronx","Manhattan","Staten Island","Brooklyn","Queens"))
```

## Normalize data
```{r}
norm_varb <- function(X_in) {
  (X_in - min(X_in, na.rm = TRUE))/( max(X_in, na.rm = TRUE) - min(X_in, na.rm = TRUE) )
}
```

####clear data
```{r}
annual_household_cost <-COSTELEC+COSTFUEL+COSTGAS+COSTWATR
norm_inc_tot <-norm_varb(INCTOT)
norm_annual_household_cost <-norm_varb(annual_household_cost)

```

##Create data frame
Here our sample size is 13112, 5 variables are selected to classify which borough may people come from.
```{r}
data_use_prelim <-data.frame(norm_inc_tot,norm_annual_household_cost)
good_obs_data_use <-complete.cases(data_use_prelim,borough_f)
dat_use <-subset(data_use_prelim,good_obs_data_use)
y_use <-subset(borough_f,good_obs_data_use)
```

##Create train data set and test data set. here we try to use 70%of the data selected as our train data and the rest of 30% as the test data set.
```{r}
set.seed(12345)
NN_obs <- sum(good_obs_data_use ==1)
select1 <-runif(NN_obs)<0.7
train_data <- subset(dat_use,select1)
test_data <-subset(dat_use,!select1)
cl_data <-y_use[select1]  ##matrix of classes of the K
true_data <-y_use[!select1]
```


##run the data and analyze 
```{r}
summary(cl_data)
```

```{r}
prop.table(summary(cl_data))
```

```{r}
summary(train_data)
summary(test_data)
```

```{r}
library(class)
 for (indx in seq(1, 9, by= 2)) {
  pred_borough <- knn(train_data, test_data, cl_data, k = indx, l = 0, prob = FALSE, use.all = TRUE)
  num_correct_labels <- sum(pred_borough == true_data)
  correct_rate <- num_correct_labels/length(true_data)
  print(c(indx,correct_rate))
 }
```
  
```
```{r}

```


##estimate the accuracy of the model
```{r}
library(gmodels)
CrossTable ( x = true_data ,
            y = pred_borough,
           prop.chisq = F)
```
 
 
 the accuracy=(529+732+33+2474+1625)/13112*100%=0.396
 the accuracy of the model is weak
 ## Try to improve the accuracy of the model
 using caret to determine K or z-score to normalize data.
```
```{r}
library(caret) ## try to use caret to determine k but can not solve the problem of missing "X" value when operate knn.
set.seed(12345)
grid=expand.grid(.k=seq(1,9, by=2))
control = trainControl(method="cv")

```

```
``
```
```{r}
normalize_z=function(x_in){
  return (X_in - min(X_in, na.rm = TRUE))/sd(X_in, na.rm = TRUE) 
}
```

```
 
 
 
           